services:
  app:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      - TEMPO_ENDPOINT=tempo:4317
    depends_on:
      - tempo
    networks:
      - monitoring-network

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo/config.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo/data
    ports:
      - "3200:3200" # Tempo UI
      - "4317:4317" # OTLP gRPC
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - tempo
    networks:
      - monitoring-network

volumes:
  tempo-data:
  grafana-data:


networks:
  monitoring-network:
