name: 서버 배포

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-server:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run server
        run: sudo docker-compose up -d

      - name: Check server
        run: sudo docker-compose ps
