name: 서버 배포

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-sender:
    runs-on: sender
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker-compose up
        run: sudo docker compose --profile sender up -d

  deploy-receiver-and-monitoring:
    runs-on: receiver, monitoring
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run docker-compose up
        run: sudo docker compose --profile receiver --profile monitoring up -d
